--DELETE FROM USERS;
--ALTER SEQUENCE USERS_ID_SEQ RESTART WITH 1;


INSERT INTO USERS (NAME, EMAIL, PASSWORD) VALUES ( 'Test1', 'test1@hotmail.com', 'test123');
INSERT INTO USERS (NAME, EMAIL, PASSWORD) VALUES ( 'Test2', 'test1@hotmail.com', 'test123');
INSERT INTO USERS (NAME, EMAIL, PASSWORD) VALUES ( 'Test3', 'test1@hotmail.com', 'test123');
INSERT INTO USERS (NAME, EMAIL, PASSWORD) VALUES ( 'Test4', 'test1@hotmail.com', 'test123');

INSERT INTO PAGES (TITLE, CONTENT, BACKGROUND) VALUES ('Page1', '1', 0);
INSERT INTO PAGES (TITLE, CONTENT, BACKGROUND) VALUES ('Page1', '1', 1);