--DELETE FROM USERS;
--ALTER SEQUENCE USERS_ID_SEQ RESTART WITH 1;


INSERT INTO USERS (NAME, EMAIL, PASSWORD) VALUES ( 'Test1', 'test1@hotmail.com', 'test123');
INSERT INTO USERS (NAME, EMAIL, PASSWORD) VALUES ( 'Test2', 'test2@hotmail.com', 'test123');
INSERT INTO USERS (NAME, EMAIL, PASSWORD) VALUES ( 'Test3', 'test3@hotmail.com', 'test123');
INSERT INTO USERS (NAME, EMAIL, PASSWORD) VALUES ( 'Test4', 'test4@hotmail.com', 'test123');

INSERT INTO CATEGORIES (TITLE, USER_ID) VALUES ('Work', '1');
INSERT INTO CATEGORIES (TITLE, USER_ID) VALUES ('Work', '2');
INSERT INTO CATEGORIES (TITLE, USER_ID) VALUES ('Work', '3');
INSERT INTO CATEGORIES (TITLE, USER_ID) VALUES ('Work', '4');
INSERT INTO CATEGORIES (TITLE, USER_ID) VALUES ('Chores', '1');
INSERT INTO CATEGORIES (TITLE, USER_ID) VALUES ('Chores', '2');
INSERT INTO CATEGORIES (TITLE, USER_ID) VALUES ('Chores', '3');
INSERT INTO CATEGORIES (TITLE, USER_ID) VALUES ('Misc.', '1');
INSERT INTO CATEGORIES (TITLE, USER_ID) VALUES ('Relaxation', '1');


INSERT INTO PAGES (TITLE, CONTENT, BACKGROUND, CATEGORY_ID) VALUES ('Page1', 'Test content', 0, 1);
INSERT INTO PAGES (TITLE, CONTENT, BACKGROUND, CATEGORY_ID) VALUES ('Page2', 'Test content', 1, 1);
INSERT INTO PAGES (TITLE, CONTENT, BACKGROUND, CATEGORY_ID) VALUES ('Page3', 'Test content', 1, 2);
INSERT INTO PAGES (TITLE, CONTENT, BACKGROUND, CATEGORY_ID) VALUES ('Page4', 'Test content', 1, 2);
INSERT INTO PAGES (TITLE, CONTENT, BACKGROUND, CATEGORY_ID) VALUES ('Page5', 'Test content', 1, 2);
INSERT INTO PAGES (TITLE, CONTENT, BACKGROUND, CATEGORY_ID) VALUES ('Page6', 'Test content', 0, 3);
INSERT INTO PAGES (TITLE, CONTENT, BACKGROUND, CATEGORY_ID) VALUES ('Page7', 'Test content', 1, 3);
INSERT INTO PAGES (TITLE, CONTENT, BACKGROUND, CATEGORY_ID) VALUES ('Page8', 'Test content', 0, 2);
INSERT INTO PAGES (TITLE, CONTENT, BACKGROUND, CATEGORY_ID) VALUES ('Page9', 'Test content', 1, 2);
INSERT INTO PAGES (TITLE, CONTENT, BACKGROUND, CATEGORY_ID) VALUES ('Page10', 'Test content', 1, 4);
INSERT INTO PAGES (TITLE, CONTENT, BACKGROUND, CATEGORY_ID) VALUES ('Page11', 'Test content', 0, 4);
INSERT INTO PAGES (TITLE, CONTENT, BACKGROUND, CATEGORY_ID) VALUES ('Page12', 'Test content', 0, 5);
INSERT INTO PAGES (TITLE, CONTENT, BACKGROUND, CATEGORY_ID) VALUES ('Page13', 'Test content', 0, 6);
INSERT INTO PAGES (TITLE, CONTENT, BACKGROUND, CATEGORY_ID) VALUES ('Page14', 'Test content', 0, 7);
INSERT INTO PAGES (TITLE, CONTENT, BACKGROUND, CATEGORY_ID) VALUES ('Page15', 'Test content', 0, 8);
INSERT INTO PAGES (TITLE, CONTENT, BACKGROUND, CATEGORY_ID) VALUES ('Page16', 'Test content', 0, 9);
INSERT INTO PAGES (TITLE, CONTENT, BACKGROUND, CATEGORY_ID) VALUES ('Page17', 'Test content', 0, 8);
INSERT INTO PAGES (TITLE, CONTENT, BACKGROUND, CATEGORY_ID) VALUES ('Page18', 'Test content', 0, 7);
INSERT INTO PAGES (TITLE, CONTENT, BACKGROUND, CATEGORY_ID) VALUES ('Page19', 'Test content', 0, 6);
INSERT INTO PAGES (TITLE, CONTENT, BACKGROUND, CATEGORY_ID) VALUES ('Page20', 'Test content', 0, 5);

